[package]
name = "numerical_recipes"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"

[features]
default = ["stable"]
stable = []
nightly = []
[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]
